export type CrosswordEntry = {
  word: string
  clue: string
}

export const CROSSWORD_WORDS: CrosswordEntry[] = [
  { word: 'REACT', clue: 'Library for building user interfaces' },
  { word: 'NODE', clue: 'JavaScript runtime outside the browser' },
  { word: 'SEED', clue: 'Value that makes a random sequence repeatable' },
  { word: 'GRID', clue: 'Rows and columns of cells' },
  { word: 'CLUE', clue: 'Hint printed beside a crossword number' },
  { word: 'CODE', clue: 'Instructions a computer can run' },
  { word: 'TYPE', clue: 'Kind of value a variable holds' },
  { word: 'DATA', clue: 'Facts a program reads or stores' },
  { word: 'PORT', clue: 'Number where a server listens' },
  { word: 'API', clue: 'Contract for calling another program' },
  { word: 'ARRAY', clue: 'Ordered list of values' },
  { word: 'STACK', clue: 'Last-in, first-out collection' },
  { word: 'QUERY', clue: 'Question sent to a database' },
  { word: 'CACHE', clue: 'Fast copy kept to avoid repeating work' },
  { word: 'PIXEL', clue: 'Single dot in an image' },
  { word: 'MODEL', clue: 'Shape loaded into a 3D scene' },
  { word: 'THEME', clue: 'Set of colors for the whole page' },
  { word: 'COLOR', clue: 'Hue applied to text or a surface' },
  { word: 'STATE', clue: 'Data a component remembers between renders' },
  { word: 'EVENT', clue: 'Signal that something happened' },
  { word: 'FRAME', clue: 'One still image in an animation' },
  { word: 'STORE', clue: 'Place that keeps data after a refresh' },
  { word: 'LOCAL', clue: 'Limited to this browser, not the server' },
  { word: 'FONT', clue: 'Design of a set of letters' },
  { word: 'HTML', clue: 'Markup language for web pages' },
  { word: 'JSON', clue: 'Text format built from braces and brackets' },
  { word: 'BYTE', clue: 'Eight bits' },
  { word: 'HOOK', clue: 'Function whose name starts with use' },
  { word: 'ROUTE', clue: 'Path a request is matched against' },
  { word: 'TOKEN', clue: 'Piece of text a parser recognizes' },
  { word: 'BUILD', clue: 'Step that turns source into something you can ship' },
  { word: 'DEBUG', clue: 'Hunt down why a program misbehaves' },
  { word: 'INPUT', clue: 'Field where someone types' },
  { word: 'LABEL', clue: 'Text that names a control' },
  { word: 'INDEX', clue: 'Position of an item in a list' },
  { word: 'ASYNC', clue: 'Able to finish later without blocking' },
  { word: 'AWAIT', clue: 'Pause until a promise settles' },
  { word: 'CSS', clue: 'Language that styles a page' },
  { word: 'DOM', clue: 'Tree of elements in a document' },
  { word: 'GIT', clue: 'Tool that records changes to files' },
  { word: 'KEY', clue: 'Field that identifies a record' },
  { word: 'WEB', clue: 'Network of linked pages' },
  { word: 'APP', clue: 'Software you open and use' },
  { word: 'DAY', clue: 'Unit this puzzle uses for its seed' },
  { word: 'BROWSER', clue: 'Program that renders this page' },
  { word: 'SERVER', clue: 'Machine that answers requests' },
  { word: 'CLIENT', clue: 'Program that asks a server for data' },
  { word: 'MODULE', clue: 'File of code other files can import' },
  { word: 'OBJECT', clue: 'Value made of named fields' },
  { word: 'STRING', clue: 'Sequence of characters' },
  { word: 'NUMBER', clue: 'Numeric value, not text' },
  { word: 'CANVAS', clue: 'Surface you can draw pixels on' },
  { word: 'VECTOR', clue: 'Image made of lines instead of pixels' },
  { word: 'MATRIX', clue: 'Grid of numbers used to transform points' },
  { word: 'BUTTON', clue: 'Control you click to run an action' },
  { word: 'LAYOUT', clue: 'How elements are arranged on a page' },
  { word: 'MARGIN', clue: 'Space outside an element border' },
  { word: 'BORDER', clue: 'Line drawn around a box' },
  { word: 'PUZZLE', clue: 'Game you solve on this page' },
  { word: 'ANSWER', clue: 'Word that fits a clue' },
  { word: 'LETTER', clue: 'One character in a word' },
  { word: 'SCRIPT', clue: 'File of JavaScript' },
  { word: 'HEADER', clue: 'Block at the top of a page or request' },
  { word: 'FOOTER', clue: 'Block at the bottom of a page' },
  { word: 'SHADOW', clue: 'Soft offset copy drawn behind a box' },
  { word: 'RADIUS', clue: 'How round a corner is' },
  { word: 'ORIGIN', clue: 'Where a coordinate system starts' },
  { word: 'CAMERA', clue: 'Viewpoint of a 3D scene' },
  { word: 'SHADER', clue: 'Program that colors a 3D surface' },
  { word: 'PROMISE', clue: 'Object that represents a future value' },
  { word: 'PACKAGE', clue: 'Bundle of code you install' },
  { word: 'FUNCTION', clue: 'Named block of code you can call' },
  { word: 'COMPONENT', clue: 'Reusable piece of a React page' },
  { word: 'INTERFACE', clue: 'TypeScript description of an object shape' },
]
